server:
    port: 8080
spring:
    application:
        name: docker_test
    thymeleaf:
        mode: HTML
        cache: true
        check-template: true
        check-template-location: true
        content-type: text/html
        enabled: true
        encoding: UTF-8
        excluded-view-names: ''
        prefix: classpath:/templates/
        suffix: .html
